source $HOME/.config/nvim/install_vim_plug
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/plug-config/formatter.vim
source $HOME/.config/nvim/plug-config/commentary.vim
source $HOME/.config/nvim/plug-config/indentguides.vim
source $HOME/.config/nvim/plug-config/telescope.vim
source $HOME/.config/nvim/plug-config/nvim-tree.vim
source $HOME/.config/nvim/plug-config/treesitter.vim
" source $HOME/.config/nvim/plug-config/nvim-compe.vim
source $HOME/.config/nvim/plug-config/bufferline.vim
source $HOME/.config/nvim/plug-config/gitsigns.vim
source $HOME/.config/nvim/plug-config/airline.vim
source $HOME/.config/nvim/plug-config/lspconfig.vim
source $HOME/.config/nvim/plug-config/lspsaga.vim
source $HOME/.config/nvim/plug-config/terraform-lsp.vim
source $HOME/.config/nvim/plug-config/bash-lsp.vim
source $HOME/.config/nvim/plug-config/diagnostics.vim
source $HOME/.config/nvim/themes/airline.vim
